name: Environment Variable - Secrets

on: workflow_dispatch

jobs:
  secrets-test:
    runs-on: ubuntu-latest
    steps:
      - name: access to secrets
        run: |
          echo "JWT_SECRET=$JWT_SECRET" >> .env
        with:
          files: ./src/main/resources/application-local.yml
        env:
          jwt.secret: ${{secrets.JWT_SECRET}}