name: Environment Variable - Secrets

on: workflow_dispatch

jobs:
  secrets-test:
    runs-on: ubuntu-latest
    steps:
      - name: access to secrets
        run: |
          echo "JWT_SECRET=$JWT_SECRET" >> .env
        env:
          MAP_API_KEY: ${{secrets.JWT_SECRET}}