spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stargram?useSSL=false&&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qlehfdl4054
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:h2:tcp://localhost/~/eunstargram
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
  # show_sql: true
        format_sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: true

# fetch API 로 multipart-form 형식으로 요청보낼 시 server 에서 multipartFile 의 사이즈가 1MB가 디폴트
# 그래서 사이즈 크기를 조절해줘야 됨(10MB 로 조정)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# secret properties
  profiles:
    include: secret

#redis
#  redis:
#    host: localhost
#    port: 6379


com:
  upload:
    path: D:/

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

